spring:
  application:
    name: try-kafka-streams
  kafka:
    streams:
      properties:
        commit:
          interval:
            # make it more interactive
            ms: 5000
      state-dir: state